#%RAML 1.0 ResourceType
post:
  description: <<recordDescription>>
  body:
    application/json:
      example: <<recordExample>>
  responses:
    200:
      body:
        application/json:
          example: {
            "result":"super success"  
          }